package Client.Enum;

public enum RequestType {
    USER_BY_LOGIN_AND_PASS, USER_BY_LOGIN,LOGIN_USER, SIGN_UP_USER,
    COMPANY_ALL,
    COMPANY_BY_ID,
    SHOW_TRANSACTIONS, ADD_TRANSACTIONS, DELETE_TRANSACTIONS,
    UPDATE_TRANSACTIONS,
    SHOW_COMPANY, ADD_COMPANY, DELETE_COMPANY, UPDATE_COMPANY,
    SHOW_PRODUCT, ADD_PRODUCT, DELETE_PRODUCT, UPDATE_PRODUCT,
    SHOW_USER, ADD_USER, DELETE_USER, UPDATE_USER,
    SHOW_DELIVERY, ADD_DELIVERY, DELETE_DELIVERY, UPDATE_DELIVERY,

    GET_USER_INFO,
    SHOW_USER_TRANSACTION, ADD_USER_TRANSACTION, DELETE_USER_TRANSACTIONS, UPDATE_USER_TRANSACTIONS,
    TRANSACTION_BY_IDCOMPANY, PRODUCT_TRANSACTION,
    DIAGRAM,
    EDIT_USER_BY_LOGIN
}
